[package]
name = "wv"
version = "0.1.0"
edition = "2021"

[lib]
name="wv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry="0.20"
anyhow="1"
log="0.4"
tokio={version="1", features=["sync"]}